version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.3
    - 24.1.4
    - 24.1.5
    - 24.1.6
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 2.34.0
    - 4.15.1
    - 4.15.2
  - dependency-name: auth0-js
    versions:
    - 9.14.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.10.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@types/algoliasearch"
    versions:
    - 3.34.11
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
