language: node_js
node_js:
  - "12"
notifications:
  slack: signalvnoise:BrQfXTzaT5BqT4qOKNSRmMYM
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls
