language: node_js
cache: yarn
node_js:
  - "12"
notifications:
  slack: signalvnoise:BrQfXTzaT5BqT4qOKNSRmMYM
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn run coverage
